/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmployabilityRouteImport } from './routes/employability'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SkillGapRouteImport } from './routes/skill-gap'
import { Route as InterviewLiveRouteImport } from './routes/interview.live'
import { Route as InterviewSetupRouteImport } from './routes/interview.setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployabilityRoute = EmployabilityRouteImport.update({
  id: '/employability',
  path: '/employability',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillGapRoute = SkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewLiveRoute = InterviewLiveRouteImport.update({
  id: '/interview/live',
  path: '/interview/live',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewSetupRoute = InterviewSetupRouteImport.update({
  id: '/interview/setup',
  path: '/interview/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employability': typeof EmployabilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/recruiter': typeof RecruiterRoute
  '/report': typeof ReportRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/skill-gap': typeof SkillGapRoute
  '/interview/live': typeof InterviewLiveRoute
  '/interview/setup': typeof InterviewSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employability': typeof EmployabilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/recruiter': typeof RecruiterRoute
  '/report': typeof ReportRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/skill-gap': typeof SkillGapRoute
  '/interview/live': typeof InterviewLiveRoute
  '/interview/setup': typeof InterviewSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/employability': typeof EmployabilityRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/recommendations': typeof RecommendationsRoute
  '/recruiter': typeof RecruiterRoute
  '/report': typeof ReportRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/skill-gap': typeof SkillGapRoute
  '/interview/live': typeof InterviewLiveRoute
  '/interview/setup': typeof InterviewSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/employability'
    | '/forgot-password'
    | '/login'
    | '/recommendations'
    | '/recruiter'
    | '/report'
    | '/resume'
    | '/settings'
    | '/signup'
    | '/skill-gap'
    | '/interview/live'
    | '/interview/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/employability'
    | '/forgot-password'
    | '/login'
    | '/recommendations'
    | '/recruiter'
    | '/report'
    | '/resume'
    | '/settings'
    | '/signup'
    | '/skill-gap'
    | '/interview/live'
    | '/interview/setup'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/employability'
    | '/forgot-password'
    | '/login'
    | '/recommendations'
    | '/recruiter'
    | '/report'
    | '/resume'
    | '/settings'
    | '/signup'
    | '/skill-gap'
    | '/interview/live'
    | '/interview/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EmployabilityRoute: typeof EmployabilityRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RecruiterRoute: typeof RecruiterRoute
  ReportRoute: typeof ReportRoute
  ResumeRoute: typeof ResumeRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SkillGapRoute: typeof SkillGapRoute
  InterviewLiveRoute: typeof InterviewLiveRoute
  InterviewSetupRoute: typeof InterviewSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employability': {
      id: '/employability'
      path: '/employability'
      fullPath: '/employability'
      preLoaderRoute: typeof EmployabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-gap': {
      id: '/skill-gap'
      path: '/skill-gap'
      fullPath: '/skill-gap'
      preLoaderRoute: typeof SkillGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/live': {
      id: '/interview/live'
      path: '/interview/live'
      fullPath: '/interview/live'
      preLoaderRoute: typeof InterviewLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/setup': {
      id: '/interview/setup'
      path: '/interview/setup'
      fullPath: '/interview/setup'
      preLoaderRoute: typeof InterviewSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EmployabilityRoute: EmployabilityRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RecommendationsRoute: RecommendationsRoute,
  RecruiterRoute: RecruiterRoute,
  ReportRoute: ReportRoute,
  ResumeRoute: ResumeRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SkillGapRoute: SkillGapRoute,
  InterviewLiveRoute: InterviewLiveRoute,
  InterviewSetupRoute: InterviewSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
